# Generated by Django 2.2.1 on 2020-02-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('checksum', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_folder', models.CharField(max_length=4096)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('show_files', models.BooleanField(default=False)),
                ('background_image', models.CharField(max_length=4096)),
            ],
        ),
    ]
