# Generated by Django 2.2.1 on 2020-02-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='background_image',
        ),
    ]
