# Generated by Django 2.2.1 on 2019-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
