# Generated by Django 2.2.1 on 2020-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_usersettings_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='background_image',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
