# Generated by Django 2.2.1 on 2019-05-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190529_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='checksum',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
