# Generated by Django 2.2.1 on 2019-06-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_uploadfile_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadFile')),
            ],
        ),
    ]
